### ISSUE TITLE
Problems with running the bot.

### ISSUE THREAD

**Issue by Torq07** [MaximAbramchuck/ruby-telegram-bot-boilerplate#1]
Hi,
First of all i want to say that you have been doing great work, Maxim! 
I don't know why in my case when i'm trying to run the bot i've got this error:

> bin/bot
> D, [2016-03-04T11:20:54.449126 #13049] DEBUG -- : Starting telegram bot
> /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:344:in `validate': HTTP redirects too deep (HTTParty::RedirectionTooDeep)
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:113:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:131:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:131:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:131:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:131:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:291:in `handle_response'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty/request.rb:131:in`perform'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in`post'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/api.rb:45:in `call'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/api.rb:40:in`method_missing'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:34:in `fetch_updates'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:29:in`listen'
>     from bin/bot:17:in `block in <main>'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:22:in`run'
>     from /home/torq07/.rvm/gems/ruby-2.2.1/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:10:in `run'
>     from bin/bot:16:in`<main>'

I thought it' because of old version of telegram-ruby-bot, so i'm updated gem to v0.4.1 but it not help.

**Comment by Torq07** [comment]
Ok, sorry, problem solved. It was on my side. Thanks anyway!)

**Comment by MaksimAbramchuk** [comment]
@Torq07 I'm glad that you've solved the problem :) Good luck!
