### ISSUE TITLE
Error installing json (1.8.3) using bundler

### ISSUE THREAD

**Issue by MalekMFS** [MaximAbramchuck/ruby-telegram-bot-boilerplate#13]
Hi,
I have error installing gems using `bundle install`. both on windows and ubuntu, both on Ruby 2.6.6 and Ruby 2.4.9.

doing `bundle install` gives this:
https://pastebin.com/0bHHg3Hq

and trying to install  `gem install json -v '1.8.3' --source 'https://rubygems.org/'` gives this error:
https://pastebin.com/DehCa9tS

similar error on windows and similar on Ruby 2.4.9

best regards

**Comment by nhcfk** [comment]
Why not just deleting `gemfile.lock` and then bundling?
