### ISSUE TITLE
How do you store state?

### ISSUE THREAD

**Issue by ackerleytng** [MaximAbramchuck/ruby-telegram-bot-boilerplate#4]
Hi! If we want the bot to reply differently while in different states, how should we store state, given this starter kit? Do we use the database to associate the state and the telegram uid?

**Comment by MaksimAbramchuk** [comment]
Awesome question, buddy!
We do use a basic class named BotCommand and create a lot of subclasses for it for each the command. And for the user we just store the current step in a user model field.
Actually, I can't explain the whole architecture here, so, how do you think, @ackerleytng, will it be interesting to read blog post about this?

**Comment by ackerleytng** [comment]
Yes please do write a blog post about this! Thanks!

**Comment by MaksimAbramchuk** [comment]
@ackerleytng I'll notify you when it will be ready

**Comment by MaksimAbramchuk** [comment]
@ackerleytng It's published!
https://medium.com/@MaximAbramchuk/full-guide-on-creating-statefull-telegram-bot-523def0a7930
Recommend to your friends if it was helpful article :)

**Comment by ackerleytng** [comment]
Thank you! So basically it's storing json in the database. I also tried something like this, but json is a really good idea. Another issue I faced was about clearing the data. How would I know that the user tired of this session? Most of the time users would just stop talking to the bot, so would you use timestamps and then clear data if it has been a long time since the data was last accessed?

**Comment by ackerleytng** [comment]
They may not necessarily start a session with the start command too.

**Comment by MaksimAbramchuk** [comment]
@ackerleytng You can not be sure that user have stopped his session. You can just assume that they have dropped out of their of session if they was not talking to bot for 2 weeks for example, and clear the user data by yourself.
