### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by AYastrebov** [MaximAbramchuck/ruby-telegram-bot-boilerplate#5]
Can it be deployed to Heroku?

**Comment by MaksimAbramchuk** [comment]
Actually, for Heroku, I do not suggest to use this boilerplate. It will be much better to setup a Rails app with telegram webhooks. Long-polling sucks.

**Comment by MaksimAbramchuk** [comment]
@AYastrebov 
https://medium.com/@MaximAbramchuk/full-guide-on-creating-statefull-telegram-bot-523def0a7930
Here is the link to my full guide on creating Telegram bot with Rails and Webhooks API. Check it out and recommend to friends if it was helpful :)

I also share my thoughts about bots/bot development on my Telegram channel: https://t.me/botcube
