### ISSUE TITLE
How to Commands with arguments

### ISSUE THREAD

**Issue by JorgeDDW** [MaximAbramchuck/ruby-telegram-bot-boilerplate#6]
Sorry for my noob question but!

How can i create a command with arguments? example:
`/car Honda`

and the bot answer a list with all the Honda models?

**Comment by MaksimAbramchuk** [comment]
I have not seen any bots working like this. I think the more preferable way is:

= /car
= Which car models you want to see?
= Honda

And the bot answer a list with all the Honda models.

Does it make sense to you?

**Comment by JorgeDDW** [comment]
Yeah I got it,  

what's the way to approach in order for the bot to reply any message?

**Comment by MaksimAbramchuk** [comment]
@JorgeDDW I suggest you to read my article about creating Telegram bot
https://medium.com/@MaximAbramchuk/full-guide-on-creating-statefull-telegram-bot-523def0a7930#.77nisidjv
Hope it will help!
