### ISSUE TITLE
 StandardError: Directly inheriting from ActiveRecord::Migration is not supported.

### ISSUE THREAD

**Issue by Coolnesss** [MaximAbramchuck/ruby-telegram-bot-boilerplate#8]
Hey, thanks for the great boilerplate. Upon setting up the database, I get 

```ruby
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
``` 

Running Ruby 2.4.0

This is easily fixed though, by changing the following line

https://github.com/MaximAbramchuck/ruby-telegram-bot-starter-kit/blob/master/db/migrate/001_create_users.rb#L1

to e.g
`class CreateUsers < ActiveRecord::Migration[5.0]`  

for Rails 5

**Comment by MaksimAbramchuk** [comment]
Feel free to open a pull request to fix this ;)

**Comment by Coolnesss** [comment]
@MaximAbramchuck sure, no problem. However, I'm unsure as to how to fix it for everyone, since the change needs to be done based on one's Rails version. Should we just go with the latest Rails?
